### ISSUE TITLE
Misc App Todos

### ISSUE THREAD

**Issue by aydinzahedi** [StanfordBDHG/PediatricAppleWatchStudy#39]
### Use Case

Miscellaneous features that were discussed for the app

### Tasks

- [x] Keep a list of recorded EKGs in the app even after it closes
- [x] Upload EKGs even when app is not running
- [x] Confirmation of the consent document emailed to the participant? Is a PDF Export possible or some sort of receipt?

**Comment by reddyrose** [comment]
Additional Task:

- [x] Verify Symptom upload, added after EKG is recorded

**Comment by PSchmiedmayer** [comment]
#42 Adds an option to get a copy of the consent document in the consent step (export button).
The rest of the elements here are on the TODO list for #42
